RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
DATA_PATH: 'data'
DB_FAISS_PATH: 'vectorstore\db_faiss'
MODEL_BIN_DIR: 'models'
MAX_NEW_TOKENS: 512
TEMPERATURE: 0.01
DEVICE: 'cpu'
